name: Update Streak Stats and Snake Animation

on:
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  buildSnake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Candy-Tree
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  updateReadme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create src directory
        run: | 
          mkdir -p src

      - name: Save Streak SVG
        run: |
          curl -L "https://streak-stats.demolab.com?user=Candy-Tree&theme=dark&hide_border=true&border_radius=20" \
            -o src/streak.svg
          
          if [ ! -s src/streak.svg ]; then
            echo "Error: Failed to download streak stats SVG"
            exit 1
          fi
          
          echo "Successfully downloaded streak stats SVG"

      - name: Save StatCard SVG
        run: |
          curl -L "https://github-readme-stats-8c11-kangseokjoos-projects.vercel.app/api?username=Candy-Tree&hide=stars,issues&include_all_commits=true&show_icons=true&locale=en&border_radius=20&theme=dracula#gh-dark-mode-only" \
            -o src/statCard.svg
          
          if [ ! -s src/statCard.svg ]; then
            echo "Error: Failed to download stat card SVG"
            exit 1
          fi
          
          echo "Successfully downloaded stat card SVG"

      - name: Save MostUsed SVG
        run: |
          curl -L "https://github-readme-stats-8c11-kangseokjoos-projects.vercel.app/api/top-langs/?username=Candy-Tree&layout=compact&include_all_commits=true" \
            -o src/mostUsed.svg
          
          if [ ! -s src/mostUsed.svg ]; then
            echo "Error: Failed to download mostUsed stats SVG"
            exit 1
          fi
          
          echo "Successfully downloaded mostUsed stats SVG"

      - name: Save ContributionGraph SVG
        run: |
          curl -L "https://github-readme-activity-graph.vercel.app/graph?username=Candy-Tree&theme=xcode&radius=16&area=true" \
            -o src/contributionGraph.svg
          
          if [ ! -s src/contributionGraph.svg ]; then
            echo "Error: Failed to download contributionGraph SVG"
            exit 1
          fi
          
          echo "Successfully downloaded contributionGraph SVG"

#      - name: Check for changes
#        id: check_changes
#        run: |
#          if git diff --quiet src/streak.svg; then
#            echo "No changes detected in streak.svg"
#            echo "has_changes=false" >> $GITHUB_OUTPUT
#          else
#            echo "Changes detected in streak.svg"
#            echo "has_changes=true" >> $GITHUB_OUTPUT
#          fi

      - name: Update README.md
        run: |
          BRANCH_NAME="refs/heads/output" 
          SVG_FILE="github-snake-dark.svg" 
          SVG_LINK="https://raw.githubusercontent.com/${{ github.repository }}/${BRANCH_NAME}/${SVG_FILE}"

          sed -i '$d' README.md
          echo "![SVG Link]($SVG_LINK)" >> README.md
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add *
          # 이전 커밋 정보 확인
          LAST_COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          
          # 이전 커밋이 같은 bot의 자동 업데이트인 경우 amend
          if [[ "$LAST_COMMIT_AUTHOR" == "github-actions[bot]" ]] && \
             [[ "$LAST_COMMIT_MESSAGE" == "Update SVGs" || \
                "$LAST_COMMIT_MESSAGE" == "Update stats and animations" ]]; then
            echo "Amending previous automatic commit..."
            git commit --amend -m "Update SVGs" --no-edit
          else
            echo "Creating new commit..."
            git commit -m "Update SVGs"
          fi
          
          git push --force-with-lease
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}